// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using WebApplication1.DBContext;

#nullable disable

namespace WebApplication1.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.13")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("WebApplication1.Models.Cosmetic", b =>
                {
                    b.Property<string>("id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("brand")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("image")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("price")
                        .HasColumnType("float");

                    b.HasKey("id");

                    b.ToTable("cosmetics");

                    b.HasData(
                        new
                        {
                            id = "a0405df3-5376-41e6-9e22-beee7f049ff4",
                            brand = "GuCci",
                            description = "this is miror",
                            image = "https://m.media-amazon.com/images/I/51d3KvJwdAL._SL1000_.jpg",
                            name = "Miror",
                            price = 99.989999999999995
                        },
                        new
                        {
                            id = "17c0692d-e6d9-4874-a860-a7f8f10742e7",
                            brand = "GuCci",
                            description = "this is Lip Gloss",
                            image = "https://m.media-amazon.com/images/I/51gD8c5l6GL._SL1500_.jpg",
                            name = "Lip Gloss",
                            price = 99.989999999999995
                        },
                        new
                        {
                            id = "c1fcc190-e767-4757-b87f-9c140925c089",
                            brand = "GuCci",
                            description = "this is Maskra",
                            image = "https://www.shutterstock.com/image-illustration/blank-eyeliner-mascara-tube-golden-260nw-2145996573.jpg",
                            name = "Maskra",
                            price = 99.989999999999995
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
